.PHONY: clean All

All:
	@echo "----------Building project:[ Split - Debug ]----------"
	@cd "Split" && "$(MAKE)" -f  "Split.mk"
clean:
	@echo "----------Cleaning project:[ Split - Debug ]----------"
	@cd "Split" && "$(MAKE)" -f  "Split.mk" clean
