.PHONY: clean All

All:
	@echo "----------Building project:[ SplitTests - Debug ]----------"
	@cd "SplitTests" && "$(MAKE)" -f  "SplitTests.mk"
clean:
	@echo "----------Cleaning project:[ SplitTests - Debug ]----------"
	@cd "SplitTests" && "$(MAKE)" -f  "SplitTests.mk" clean
